### ISSUE TITLE
Download of precomputed features

### ISSUE THREAD

**Issue by jpeyre** [peteanderson80/Up-Down-Captioner#12]
Hi, 

Thank you for releasing this code and data !
I do not manage to download the pre-computed features : the download rate is slow (~400K/s) and interrupted by read errors. An issue is that wget -c does not work, thus the download always re-starts from the beginning so I am blocked in infinite loop! Would there be another way to provide the features ?

Thanks a lot, 

Julia

**Comment by nicholasmireles** [comment]
Julia,
If you haven't yet solved this, you could always get the bottom-up part of this model and generate the features yourself. Other than that or re-hosting the features somewhere else, you might have to work out that issue with your ISP.

**Comment by jpeyre** [comment]
Thank you for your answer! Yes eventually I am re-computing the features, this seems the most simple solution.
