### ISSUE TITLE
The link of pretrained faster-rcnn and caption model seems invalid

### ISSUE THREAD

**Issue by MinglangQiao** [peteanderson80/Up-Down-Captioner#22]
Hi, perter, thanks for sharing your code. However, the link of pretrained model in ./scripts/demo.ipynb seems invalid. Could you please update that? Thank you very much!

**Comment by EmilRais** [comment]
If you check the file history of scripts/demo.ipynb you will see google storage links were previously used. You can still use those, they actually work - they're marked as "requester pays", so you'll have to pay for the bandwidth used to transfer them but it shouldn't amount to much.

**Comment by MinglangQiao** [comment]
ok, thanks for your response.
