### ISSUE TITLE
Permission for downloading pretrained image features

### ISSUE THREAD

**Issue by kevgeo** [peteanderson80/Up-Down-Captioner#3]
Hi Peter,

I clicked on the [2014 Train/Val Image Features (120K / 23GB)](https://storage.googleapis.com/bottom-up-attention/trainval.zip) link to download pretrained images but I am unable to which I believe is due to the permissions set for public users. I have attached below a screenshot of the problem I'm facing.

![issue1](https://user-images.githubusercontent.com/8247966/40358564-3e27ac50-5ddd-11e8-9bf3-564939bf6148.png)

The same problem occurs for [2014 Testing Image Features (40K / 7.3GB)](https://storage.googleapis.com/bottom-up-attention/test2014.zip) link.

**Comment by kevgeo** [comment]
It is fine. I have found the link for the pretrained features in your [bottom-up-attention
](https://github.com/peteanderson80/bottom-up-attention) github repo readme file.

**Comment by peteanderson80** [comment]
Great, no problem.

**Comment by peteanderson80** [comment]
I will update the links I had forgotten about these.
