### ISSUE TITLE
About lstm_iter_60000.caffemodel.h5 file

### ISSUE THREAD

**Issue by quangvy2703** [peteanderson80/Up-Down-Captioner#7]

**Comment by nicholasmireles** [comment]
@akira-l I'm running the training script now and get the same error as you. How did you generate the solverstate.h5 file that you said fixed the problem?

**Comment by Cestbon123** [comment]
> Firstly, you should run the script scripts/demo.ipynb, it will download faster_rcnn model and caption_weight model automatically. Or, you can get the download link from this script for download manually. After that, you can run training script.

Can you send me the caption_weight model?The link seems to be broken.Thank you very much

**Comment by nyj-ocean** [comment]
@Cestbon123 
have you download the caption_weight?
if so ,can you share me caption_weight?
